name: Release

on:
  release:
    types: [ published ]
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    env:
      GRADLE_OPTS: "-Xmx6g -Xms4g"
    steps:
      - uses: actions/checkout@v2
      - name: Setup Java 8
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 8
          cache: gradle
      - name: Semantic Version
        id: version
        uses: ncipollo/semantic-version-action@v1
      - name: Decode PGP
        id: write_file
        uses: timheuer/base64-to-file@v1
        with:
          fileName: 'secret.pgp'
          encodedString: ${{ secrets.SIGNING_SECRET_KEY_BASE64 }}
      - name: Release Micronaut 1.x
        uses: eskatos/gradle-command-action@v1
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          SIGNING_SECRET_KEY_PATH: ${{ steps.write_file.outputs.filePath }}
        with:
          arguments: publishToSonatype closeAndReleaseSonatypeStagingRepository -Pversion=${{ steps.version.outputs.tag }}-micronaut-1.0 -Prelease=true -Dorg.ajoberstar.grgit.auth.username=${{ secrets.AGORAPULSE_BOT_PERSONAL_TOKEN }} --stacktrace
      - name: Release Micronaut 2.x
        uses: eskatos/gradle-command-action@v1
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          SIGNING_SECRET_KEY_PATH: ${{ steps.write_file.outputs.filePath }}
        with:
          arguments: publishToSonatype closeAndReleaseSonatypeStagingRepository -Pversion=${{ steps.version.outputs.tag }}-micronaut-2.0 --stacktrace -PmicronautVersion=2.5.13 -PspockVersion=2.0-groovy-3.0 -PgroovyVersion=3.0.9
      - name: Release Micronaut 3.x
        uses: eskatos/gradle-command-action@v1
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          SIGNING_SECRET_KEY_PATH: ${{ steps.write_file.outputs.filePath }}
        with:
          arguments: gitPublishPush publishToSonatype closeAndReleaseSonatypeStagingRepository -Pversion=${{ steps.version.outputs.tag }}-micronaut-3.0 --stacktrace -PmicronautVersion=3.2.1 -PspockVersion=2.0-groovy-3.0 -PgroovyVersion=3.0.9 -Dorg.ajoberstar.grgit.auth.username=${{ secrets.AGORAPULSE_BOT_PERSONAL_TOKEN }}
  ping:
    name: Notify Upstream Repositories
    runs-on: ubuntu-latest
    needs: [ release ]
    strategy:
      matrix:
        repository:
          - agorapulse/agorapulse-bom
          - agorapulse/agorapulse-oss
    steps:
      - uses: actions/checkout@v1
      - name: Semantic Version
        id: version
        uses: ncipollo/semantic-version-action@v1
      - name: Dispatch to ${{ matrix.repository }}
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.AGORAPULSE_BOT_PERSONAL_TOKEN }}
          repository: ${{ matrix.repository }}
          event-type: ap-new-version-released-event
          client-payload: '{ "group": "com.agorapulse", "module": "micronaut-snitch", "version": "${{ steps.version.outputs.tag }}-micronaut-1.0", "property" : "micronaut.snitch.version", "github" : ${{ toJson(github) }} }'
